#!/bin/bash
#MOAB/Torque submission script for SciNet GPC

## queue/PBS settings
#PBS -l nodes=1:m32g:ppn=8
#PBS -l walltime=1:00:00
# merge standard error and output stream
#PBS -j oe
#PBS -o $PBS_JOBNAME.$PBS_JOBID.out
##PBS -e $PBS_JOBNAME.$PBS_JOBID.err
# send email if abort (nbae)
#PBS -M aerler@atmosp.physics.utoronto.ca
#PBS -m ae
# job name
#PBS -N test_WPS
## submit to queue (NB: this has to be the last PBS line!)
# batch (default), debug, largemem
#PBS -q batch


## job settings
export SCRIPTNAME="run_${PBS_JOBNAME}.pbs" # WPS suffix assumed
export CLEARWDIR=0 # do not clear working director
# run configuration
export NODES=1 # only one for WPS!
export TASKS=16 # number of MPI task per node (Hpyerthreading?)
export THREADS=1 # number of OpenMP threads
# directory setup
export INIDIR="${PBS_O_WORKDIR}"
export RUNNAME="${PBS_JOBNAME%_*}" # strip WPS suffix
export WORKDIR="${INIDIR}/${RUNNAME}/"

# optional arguments $RUNPYWPS, $RUNREAL, $RAMIN, $RAMOUT
export RUNPYWPS=1
export RUNREAL=1
export RAMIN=1
export RAMOUT=0
# folders: $METDATA, $REALIN, $REALOUT
export METDATA="${INIDIR}/metgrid/"
export REALOUT="${WORKDIR}"

# whether or not to clear job folder (default: yes)
if [[ -z "$CLEARWDIR" ]]; then CLEARWDIR=1; fi


## setup environment
cd "${INIDIR}"
source setup_GPC.sh # load machine-specific stuff


## begin job

# start timing
echo
echo '   ***   Start Time    ***   '
date
echo 

# prepare directory
cd "${INIDIR}"
./prepWorkDir.sh

# run script
cd "${INIDIR}"
./execWPS.sh

# end timing
echo
echo '    ***    End Time    *** '
date
echo
