#!/bin/bash
# Andre R. Erler, 06/09/2013
# script to list status of active experiments on SciNet

# list of active experiment by machine
GPC_JOBS='' 
TCS_JOBS='max-ctrl-2050 max-ens-B max-ens-B-2050 max-gulf cfsr-max new-ctrl new-nogulf new-noah'
P7_JOBS='max-ens-A max-ens-A-2050 max-ens-C max-ens-C-2050 max-seaice cfsr-new nmpnew-ctrl'

# function that does the actual check
function CHECK {
  local JOBS=${1} # list of running experiments
  local LISTING=${2} # queue status output
  local MAC=${3} # machine we are checking
  for E in ${JOBS}
    do
      if [[ -z $( echo ${LISTING} | grep ${E} ) ]]
	then 
	  echo
	  echo "Experiment ${E} on ${MAC} is not running!"
	  MIA=$(( $MIA + 1 )) # modifies global counter!
      else
	  #echo "Experiment ${E} on ${MAC} is running!"
	  OK=$(( $OK + 1 )) # modifies global counter!
      fi
  done
} # CHECK

# query machine for running jobs
OK=0 # counter for running jobs
MIA=0 # counter for crashed jobs

# GPC
GPC_LIST=$( ssh gpc01 'showq -nu aerler | grep aerler' )
CHECK "${GPC_JOBS}" "${GPC_LIST}" 'GPC'

# TCS
TCS_LIST=$( ssh tcs01 'llq -l | grep -B 3 '\''Owner: aerler'\''' )
CHECK "${TCS_JOBS}" "${TCS_LIST}" 'TCS'

# P7
P7_LIST=$( ssh p701 'llq -m | grep '\''Job Name'\''' )
CHECK "${P7_JOBS}" "${P7_LIST}" 'P7'

# report summary
echo 
if [ ${MIA} == 0 ]
  then
    echo "   <<<   All ${OK} jobs are running!  >>>   "
elif [ ${OK} == 0 ]
  then
    echo "   ###   All ${MIA} jobs crashed!!!  ###   "
else
    echo "   ===   ${MIA} jobs crashed, ${OK} running...  ===   "
fi # summary
echo
