#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -q archive
#PBS -N ar_benchmark
#PBS -j oe
#PBS -m e

set -o pipefail

SRC="${SCRATCH}/HPSS-test"

hsi rm ${ARCHIVE}/test.*
hsi ls -l ${ARCHIVE}
cd "${SRC}"

echo
echo
echo ***   HPSS Benchmark   ***
echo

echo ***   HSI (plain)   ***
time -p hsi -q cput "${SRC}/test.nc" : "${ARCHIVE}/test.plain"
echo
echo ***   TAR (only)   ***
time -p tar -c test.nc | hsi -q cput - : "${ARCHIVE}/test.tar"
echo
echo ***   GZIP   ***
time -p tar -cz test.nc | hsi -q cput - : "${ARCHIVE}/test.tar.gz"
echo
echo ***   BZIP   ***
time -p tar -cj test.nc | hsi -q cput - : "${ARCHIVE}/test.tar.bz2"
echo
echo ***   LZMA   ***
time -p tar -c --lzma test.nc | hsi -q cput - : "${ARCHIVE}/test.tar.lzma"
echo
echo ***   ZIP   ***
time -p tar c test.nc | zip | hsi -q cput - : "${ARCHIVE}/test.tar.zip"

echo
echo
echo ***   GPFS Benchmark   ***
echo

echo ***   copy (plain)   ***
time -p cp test.nc "${SRC}/test.plain"
echo
echo ***   TAR (only)   ***
time -p tar -cf "${SRC}/test.tar" test.nc
echo
echo ***   GZIP   ***
time -p tar -czf "${SRC}/test.tar.gz" test.nc
echo
echo ***   BZIP   ***
time -p tar -cjf "${SRC}/test.tar.bz2" test.nc
echo
echo ***   LZMA   ***
time -p tar --lzma -cf "${SRC}/test.tar.lzma" test.nc 
echo
echo ***   ZIP   ***
time -p zip "${SRC}/test.tar.zip" test.nc
